### ISSUE TITLE
Find then Edit List Display

### ISSUE THREAD

**Issue by george-yeo** [AY2425S1-CS2103T-T17-4/tp#63]
# Steps to Reproduce
1. Find using a keyword that displays exactly 2 contacts
2. Edit any field of any one of the contacts displayed
3. The contact list refreshes and shows the entire contact list unexpectedly, instead of staying at showing only the 2 contacts

**Comment by ty4g1** [comment]
Regarding this issue, I think it has been done on purpose to keep the logic simple. Since otherwise after editing we would have to check again if the edited contact should be displayed in that filtered list.

![image](https://github.com/user-attachments/assets/e49e16f3-8938-4993-a105-63608ef7baa8)

**Comment by george-yeo** [comment]
That makes sense. I'm concerned if a more forgetful user for example edits one field but forgets to edit another, or if the user wanted to edit more than 1 person after a find, they would have to find to edit again. It's a small thing so I think it's fine to ignore.
