### ISSUE TITLE
Selecting a contact breaks list

### ISSUE THREAD

**Issue by george-yeo** [AY2425S1-CS2103T-T17-4/tp#91]
## Steps to Reproduce
1. Click on any contact
2. The contact list gets messed up when scrolling up and down
## Expected Outcome
Contact list remains unchanged
## Actual Outcome
The contacts go weird and the numbering is wrong
![image](https://github.com/user-attachments/assets/41cd81f3-c204-4f6a-9198-a7535d91227e)

**Comment by LOLIPOP-INTELLIGENCE** [comment]
I tried to replicate this with the changes I made on the linked branch - I think this branch resolves the issue. Can you check?
